server:
  tomcat:
    # 最大等待数,默认100
    accept-count: 100
    #最大链接数,默认8192。当为-1 不限制连接数
    max-connections: 8192
    threads:
      #最大线程数，默认200。一般根据CPU来的，1核≈200个。4核8G，可以配置为800
      max: 200
      #最小工作空闲线程数 默认10
      min-spare: 10


mybatis:
  typeAliasesPackage: com.nimo.shardingspheredemo.entity
  mapperLocations: classpath:mapper/*.xml

